// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sophia_FrontToBack.Data;

#nullable disable

namespace Sophia_FrontToBack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230405000508_AddSliderTable")]
    partial class AddSliderTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Sophia_FrontToBack.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Up to 70%",
                            Image = "Slide1.jpg",
                            Title = "HUGE SALE"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Check the promotion",
                            Image = "Slide2.jpg",
                            Title = "BIGGEST DISCOUNT"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dont miss it",
                            Image = "Slide3.jpg",
                            Title = "BIGGEST SALE"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Special selection",
                            Image = "Slide4.jpg",
                            Title = "OUR BEST PRODUCTS"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Only for today",
                            Image = "Slide5.jpg",
                            Title = "MASSIVE SALE"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
